name: wsissl
channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.7=py310hdf3cbec_0
  - cryptography=38.0.4=py310h597c629_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.0.140=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.0.140=0
  - cuda-nsight-compute=12.0.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.0.140=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.0.146=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.0.146=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.0.140=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - docker-pycreds=0.4.0=py_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.39.2=py310h1fa729e_0
  - freetype=2.12.1=hca18f0e_1
  - gds-tools=1.5.1.14=0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=hf484d3e_1000
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.5.1.14=0
  - libcufile-dev=1.5.1.14=0
  - libcurand=10.3.1.124=0
  - libcurand-dev=10.3.1.124=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libllvm10=10.0.1=he513fc3_3
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h753d276_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzlib=1.2.13=h166bdaf_4
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib=3.7.1=py310hff52083_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310ha2c4b55_0
  - mkl_fft=1.3.1=py310h2b4bcf5_1
  - mkl_random=1.2.2=py310h00e6091_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - nsight-compute=2022.4.1.6=0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.23.5=py310hd5efca6_0
  - numpy-base=1.23.5=py310h8e6c178_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=1.1.1t=h0b41bf4_0
  - pandas=1.5.2=py310h1128e8f_0
  - pathtools=0.1.2=py_1
  - pcre2=10.40=hc3806b6_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.6.0=pyhd8ed1ab_0
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=5.9.4=py310h5764c6d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyg=2.2.0=py310_torch_1.13.0_cu116
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cluster=1.6.0=py310_torch_1.13.0_cu116
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.0=py310_torch_1.13.0_cu116
  - pytorch-sparse=0.6.15=py310_torch_1.13.0_cu116
  - pytz=2022.7=py310h06a4308_0
  - pyyaml=6.0=py310h5764c6d_5
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - scikit-learn=1.2.0=py310h6a678d5_0
  - scipy=1.10.0=py310hd5efca6_0
  - sentry-sdk=1.15.0=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h5764c6d_1
  - setuptools=67.3.2=pyhd8ed1ab_0
  - sip=6.6.2=py310hd8f1fbe_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.40.1=h5082296_0
  - submitit=1.2.1=pyh44b312d_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=0.13.1=py310_cu116
  - torchvision=0.14.1=py310_cu116
  - tornado=6.2=py310h5764c6d_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wandb=0.13.10=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - einops==0.6.1
    - filelock==3.9.0
    - geojson==3.0.1
    - huggingface-hub==0.12.1
    - imageio==2.25.1
    - lxml==4.9.2
    - networkx==3.0
    - numpyencoder==0.3.0
    - nystrom-attention==0.0.11
    - opencv-python==4.7.0.72
    - openslide-python==1.2.0
    - packaging==23.0
    - pyqt5-sip==12.11.0
    - python-docx==0.8.11
    - pywavelets==1.4.1
    - scikit-image==0.19.3
    - tifffile==2023.2.3
    - timm==0.6.12
    - torchsummary==1.5.1
    - wsiprocess==0.9
prefix: /homes/gbontempo/.conda/envs/wsissl
