name: dasmil
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - addict=2.4.0=pyhd8ed1ab_2
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.3.0=h27087fc_1
  - blas=2.115=mkl
  - blas-devel=3.9.0=15_linux64_mkl
  - blosc=1.21.1=h83bc5f7_3
  - bottleneck=1.3.4=py39hd257fcd_1
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.1.1=h7a311fb_2
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.3=py39hf3d152e_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39hb9d737c_2
  - dask-core=2022.5.2=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - docker-pycreds=0.4.0=py_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.1=hd7ab26d_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py39hb9d737c_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.5.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.8=hff1cb4f_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.20.2=hf6a322e_1
  - gstreamer=1.20.2=hd4edc92_1
  - harfbuzz=4.2.0=h40b6f09_0
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py39h9c0c3a3_5
  - imageio=2.19.3=pyhcf75d05_0
  - jasper=2.0.33=ha77e612_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39hf939315_1
  - krb5=1.19.3=h08a2579_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.10.1=h166bdaf_0
  - libblas=3.9.0=15_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=15_linux64_mkl
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.83.1=h2283fc2_0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.111=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=15_linux64_mkl
  - liblapacke=3.9.0=15_linux64_mkl
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=he49606f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.5=py39h12858e4_8
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libpq=14.3=he2d8382_0
  - libprotobuf=3.20.1=h6239696_0
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0fcbabc_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libva=2.14.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.12=h166bdaf_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=14.0.4=he0ac6c6_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.5.2=py39hf3d152e_0
  - matplotlib-base=3.5.2=py39h700656a_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.29=h26416b9_1
  - mysql-libs=8.0.29=hbc51c84_1
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - networkx=2.8.3=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numexpr=2.7.3=py39hde0f152_1
  - numpy=1.22.4=py39hc58783e_0
  - opencv=4.5.5=py39hf3d152e_8
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openslide=3.4.1=h978ee9a_4
  - openssl=3.0.5=h166bdaf_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py39h295c915_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.1.1=py39hae2aec6_1
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - promise=2.3=py39hf3d152e_6
  - protobuf=3.20.1=py39h5a03fae_0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.5=py39hef51801_8
  - pycparser=2.21=pyhd8ed1ab_0
  - pyg=2.0.4=py39_torch_1.11.0_cu102
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py39h03dd644_4
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.12=h2660328_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-hostlist=1.21=pyh9f0ad1d_0
  - python-louvain=0.15=pyhd8ed1ab_1
  - python_abi=3.9=2_cp39
  - pytorch=1.11.0=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-cluster=1.6.0=py39_torch_1.11.0_cu102
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py39_torch_1.11.0_cu102
  - pytorch-sparse=0.6.13=py39_torch_1.11.0_cu102
  - pytorch-spline-conv=1.2.1=py39_torch_1.11.0_cu102
  - pytz=2022.1=pyhd8ed1ab_0
  - pywavelets=1.3.0=py39hd257fcd_1
  - pyyaml=6.0=py39hb9d737c_4
  - qt=5.12.9=h1304e3e_6
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-image=0.19.2=py39hde0f152_0
  - scikit-learn=1.0.2=py39h4dfa638_0
  - scipy=1.8.1=py39he49c0e8_0
  - sentry-sdk=1.5.12=pyhd8ed1ab_0
  - setproctitle=1.2.3=py39hb9d737c_0
  - shortuuid=1.0.8=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.38.5=h4ff8645_0
  - submitit=1.2.1=pyh44b312d_0
  - svt-av1=0.9.1=h27087fc_0
  - tbb=2021.5.0=h924138e_1
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.5.4=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchvision=0.12.0=py39_cu102
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - typing_extensions=4.2.0=pyha770c72_1
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zfp=0.5.5=h9c3ff4c_8
  - zlib=1.2.12=h166bdaf_0
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - autopep8==1.6.0
    - avalanche-lib==0.2.0
    - beautifulsoup4==4.11.1
    - brotli==1.0.9
    - cachetools==5.0.0
    - cython==0.29.30
    - dash==2.4.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - einops==0.4.1
    - filelock==3.7.1
    - flask==2.1.2
    - flask-compress==1.12
    - frozenlist==1.3.0
    - fvcore==0.1.5.post20220512
    - gdown==4.5.1
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - gputil==1.4.0
    - grpcio==1.46.1
    - gshell==5.6.1
    - h5py==3.6.0
    - igraph==0.9.11
    - importlib-metadata==4.11.3
    - iopath==0.1.9
    - itsdangerous==2.1.2
    - kaleido==0.2.1
    - lightning-bolts==0.5.0
    - lxml==4.9.0
    - markdown==3.3.7
    - multidict==6.0.2
    - oauthlib==3.2.0
    - openslide-python==1.1.2
    - plotly==5.8.0
    - portalocker==2.4.0
    - problog==2.2.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pydeprecate==0.3.2
    - pydot==1.4.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pysdd==0.2.10
    - pytorch-lightning==1.6.3
    - pytorch-toolbelt==0.5.2
    - pytorchcv==0.0.67
    - quadprog==0.1.11
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - setuptools==59.5.0
    - soupsieve==2.3.2.post1
    - tabulate==0.8.9
    - tenacity==8.0.1
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - texttable==1.6.4
    - timm==0.4.12
    - toml==0.10.2
    - torchmetrics==0.8.2
    - tsne-torch==1.0.1
    - wandb==0.12.16
    - werkzeug==2.1.2
    - wsiprocess==0.9
    - yarl==1.7.2
    - zipp==3.8.0
prefix: /homes/gbontempo/.conda/envs/sslwsiv2